### ISSUE TITLE
CUDA out of memory when using batch or multiprocess version

### ISSUE THREAD

**Issue by xuantengh** [cjlovering/Towards-Interpretable-Reinforcement-Learning-Using-Attention-Augmented-Agents-Replication#3]
I run `python main_mp.py` but returns CUDA out of memory error.
Is there any combination of hyper-parameters fitting in multiprocess version?

**Comment by cjlovering** [comment]
I won't be able to help much here. 

A better (but still hard to use) version of this project is here:
[https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention](https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention
)

Here's our final implementation of the network:
[https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/torchbeast/attention_net.py
](https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/torchbeast/attention_net.py
)

This should work locally / on a grid, but that won't really leverage the framework.
[https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/job_small.sh](https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/job_small.sh)

The installation/setup to get it working remotely was tough to get to work. I'd recommend looking at our source, and if anything, try an easier game than SeaQuest. We did this for a class project... choosing an easier game and getting faster results would have been a smart idea.

**Comment by xuantengh** [comment]
> I won't be able to help much here.
> 
> A better (but still hard to use) version of this project is here:
> https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention
> 
> Here's our final implementation of the network:
> [https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/torchbeast/attention_net.py ](https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/torchbeast/attention_net.py)
> 
> This should work locally / on a grid, but that won't really leverage the framework.
> https://github.com/cjlovering/interpretable-reinforcement-learning-using-attention/blob/master/job_small.sh
> 
> The installation/setup to get it working remotely was tough to get to work. I'd recommend looking at our source, and if anything, try an easier game than SeaQuest. We did this for a class project... choosing an easier game and getting faster results would have been a smart idea.

Thanks for your reply😊😊
